### ISSUE TITLE
mc!pin not working

### ISSUE THREAD

**Issue by PustakP** [emerysteele/minecraft-server-status-bot#4]
I tried the mc!pin command but it did not work. It threw this error- 
![image](https://user-images.githubusercontent.com/74170759/118637479-7a328800-b7f3-11eb-872b-b55962c85a07.png)

**Comment by emerysteele** [comment]
unable to reproduce

possibly a compatibility issue with a newer module version
I have added package.json with dependency versions to ensure compatible module versions are installed

**Comment by emerysteele** [comment]
found what is causing the issue, if the server does not have an icon set, the json will return a null value & it is not handled

will see how I can fix this problem

**Comment by emerysteele** [comment]
Fixed handling when server icon is null in v0.1.4
